### PR TITLE
Implement trim function

### PR DESCRIPTION
**Pull request by justinsalamon**
This PR will implement a trim function for jams objects as discussed in #135

---

This change is [Reviewable](https://reviewable.io/reviews/marl/jams/136)

### CODE REVIEW

**Comment by justinsalamon** [comment]
Looks like this is ready for a CR. @bmcfee (or anyone else)?

**Comment by justinsalamon** [comment]
@bmcfee are you back from crunchland yet?

**Comment by bmcfee** [comment]
> @bmcfee are you back from crunchland yet?

nope; next week okay?

**Comment by justinsalamon** [comment]
> nope; next week okay?

yeah sure, thanks!

**Comment by justinsalamon** [comment]
@bmcfee I've updated the API again based on our latest discussion, refactoring `trim()` into `trim()` and `slice()`. I've documented the new expected behavior of each function in detail [here](https://github.com/marl/jams/issues/135#issuecomment-258549709), which is probably worth reading before giving this PR a CR, which I think it's ready for again.

**Comment by bmcfee** [comment]
Review status: 0 of 2 files reviewed at latest revision, 16 unresolved discussions.

---

*[jams/core.py, line 47 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpIHJvZzjFh3fOIY1I:-KVpIHJvZzjFh3fOIY1J:bwlxg4n) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L47)):*
> ```Python
> import gzip
> import datetime
> ```

why datetime?

---

*[jams/core.py, line 897 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpFDcoJRgfHi6K5qwZ:-KVpFDcpa7DNcskcZRZa:bb9xn5f) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L897)):*
> ```Python
>         of tuples to the annotation's sandbox keyed by `sandbox.trim` which
>         documents each trim operation with a tuple `(start_time, end_time,
>         trim_start, trim_end)`.
> ```

Please break this up into a short (one-line) description and then a more structured, detailed description.

Other notes:
- `self` is not an externally meaningful variable name for object methods.
- break out the warning and exception cases with bullets so they're easily identified

---

*[jams/core.py, line 939 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpF1hh2QqKAne3BJte:-KVpF1hi6FNtl23H9wYJ:b4ykmlr) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L939)):*
> ```Python
> 
>         # The annotation must have it's duration value set for trimming
>         if self.duration is None:
> ```

Why is this an error?  The semantics of `duration=None` are that the annotation implicitly spans the full track duration as specified in `file_metadata`.

---

*[jams/core.py, line 990 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGPiOyNhSYS29F7ru:-KVpGPiOyNhSYS29F7rv:b7h0ymc) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L990)):*
> ```Python
>                                        confidence=obs['confidence'])
> 
>         if 'trim' not in ann_trimmed.sandbox.keys():
> ```

you don't need to call `.keys()` here

---

*[jams/core.py, line 995 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGZpxuJ-vzWFJFeE4:-KVpGZpy3VR1trWHcOn9:b-u64vro) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L995)):*
> ```Python
>         else:
>             ann_trimmed.sandbox.trim.append(
>                 (start_time, end_time, trim_start, trim_end))
> ```

I think trim history would make more sense as a list of dictionaries, rather than a list of tuples.

Also, your annotation construction seems to be a copy-by-reference of `sandbox`, so I think this will also populate the `trim` field in the input annotation's sandbox.  This is probably not what you intended.

---

*[jams/core.py, line 1015 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGsfxeBELqXKaKKr1:-KVpGsfxeBELqXKaKKr2:b-t7x39v) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1015)):*
> ```Python
>         trimming operation will also be documented in `Annotation.sandbox.trim`
>         as described in `Annotation.trim`.
> ```

Again, provide a short (1-sentence) docstring and then a detailed description.

---

*[jams/core.py, line 1023 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGyCIbp2Ba-Jno8JH:-KVpGyCIbp2Ba-Jno8JI:by0tls2) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1023)):*
> ```Python
>         ----------
>         start_time : float
>             The desired start time for slicing.
> ```

+"in seconds"

---

*[jams/core.py, line 1039 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpH2gA5L1UveCh6iBb:-KVpH2gA5L1UveCh6iBc:b-6t8jro) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1039)):*
> ```Python
>         sliced_ann : Annotation
>             The sliced annotation.
> ```

Add a "see also" to trim

Add an example

---

*[jams/core.py, line 1050 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpH8EltQ7pUmHN07wa:-KVpH8EltQ7pUmHN07wb:bh1zlu) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1050)):*
> ```Python
>         adjustment = ref_time - sliced_ann.time
> 
>         if sliced_ann.data is not None:
> ```

why would this ever be `None`?

---

*[jams/core.py, line 1051 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHDoOOuzgPgC4xhjY:-KVpHDoPUAOAVWevSUo-:b-d1wmkf) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1051)):*
> ```Python
> 
>         if sliced_ann.data is not None:
>             for idx in range(len(sliced_ann.data.index)):
> ```

This isn't the correct way to iterate over dataframe indices.

Instead, do
```python
for idx in sliced_ann.data.index:
```
or avoid iteration altogether:
```python
sliced_ann.data['time'] = sliced_ann.data['time'].apply(lambda x: x - pd.to_timedelta(adjustment, unit='s')
```

---

*[jams/core.py, line 1058 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHaw3gH7jiFNgbYeG:-KVpHaw3gH7jiFNgbYeH:b9031qz) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1058)):*
> ```Python
>         slice_end = ref_time + sliced_ann.duration
> 
>         if 'slice' not in sliced_ann.sandbox.keys():
> ```

no need for .keys(), and same comments as in `trim` above.

---

*[jams/core.py, line 1561 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHn7uvieNVSG1GAaD:-KVpHn7uvieNVSG1GAaE:bdqh1sc) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1561)):*
> ```Python
>             raise JamsError(
>                 'Duration must be set (jam.file_metadata.duration) before '
>                 'trimming can be performed.')
> ```

I don't see why this should be required here.

---

*[jams/core.py, line 1567 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHxBoHukpzPSZTAQX:-KVpHxBoHukpzPSZTAQY:bqyn97f) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1567)):*
> ```Python
>                 start_time > float(self.file_metadata.duration) or
>                 end_time < start_time or
>                 end_time > float(self.file_metadata.duration)):
> ```

fun fact: python supports triple comparison, so you can do `not (0 <= start_time <= self.file_metadata.duration)`

---

*[jams/core.py, line 1576 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpI6Nw8vYIQmiwWtFg:-KVpI6Nw8vYIQmiwWtFh:bnud1jh) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1576)):*
> ```Python
>         jam_trimmed = JAMS(annotations=None,
>                            file_metadata=self.file_metadata,
>                            sandbox=self.sandbox)
> ```

I think you want a deep copy here, not copy-by-reference.

---

*[jams/core.py, line 1583 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpID29D2Ai9k1HWX1d:-KVpID29D2Ai9k1HWX1e:brlj2z) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1583)):*
> ```Python
> 
>         # Document jam-level trim in top level sandbox
>         if 'trim' not in jam_trimmed.sandbox.keys():
> ```

-.keys()

---

*[tests/jams_test.py, line 732 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpIRvEsagmX55mdBRc:-KVpIRvEsagmX55mdBRd:bugoz7) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/tests/jams_test.py#L732)):*
> ```Python
> 
> def test_annotation_trim():
> ```

Please break this test into smaller test functions for each test case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/136)*

**Comment by justinsalamon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 16 unresolved discussions.

---

*[jams/core.py, line 47 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpIHJvZzjFh3fOIY1I:-KW45b81yIneMbShthFr:b-hfvos4) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L47)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> why datetime?
</details>
Thought I needed it for some conversions but ended up using pandas instead. Removed.

---

*[jams/core.py, line 897 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpFDcoJRgfHi6K5qwZ:-KW4M_JAzCOz7gqNohYZ:b-1d7xg0) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L897)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Please break this up into a short (one-line) description and then a more structured, detailed description.
> 
> Other notes:
> - `self` is not an externally meaningful variable name for object methods.
> - break out the warning and exception cases with bullets so they're easily identified
</details>
Removed references to self, broken up docstring into more manageable paragraphs, and added examples.

---

*[jams/core.py, line 939 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpF1hh2QqKAne3BJte:-KW4qql0z7muEBnVBGxI:b-54kvu6) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L939)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Why is this an error?  The semantics of `duration=None` are that the annotation implicitly spans the full track duration as specified in `file_metadata`.
</details>
I need to know the time range spanned by the annotation to compute the intersection with the trim range specified by the user, for which I need `Annotation.duration`.

Since an Annotation object can exist independently of a JAMS object, while `duration=None` means "use the jams duration", there's no way for me to access this value from inside this function (or the value may not exist).

---

*[jams/core.py, line 990 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGPiOyNhSYS29F7ru:-KW4SnxcvSjzvksq4i_U:b-4ltbie) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L990)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> you don't need to call `.keys()` here
</details>
Tried without but it breaks (problem in sandbox implementation?), leaving in for now.

---

*[jams/core.py, line 995 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGZpxuJ-vzWFJFeE4:-KW4UhiUBkoLKV9-JUkN:b-nn7csl) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L995)):*
OK, I've switched the history to be a list of dicts.

Regarding the sandbox, I don't think it's copied by reference:
```python
        # Create new annotation with same namespace/metadata
        ann_trimmed = Annotation(
            self.namespace,
            data=None,
            annotation_metadata=self.annotation_metadata,
            sandbox=self.sandbox,
            time=trim_start,
            duration=trim_end - trim_start)
```

If you try it out the sandbox of the original annotation is unchanged:
```python
>>> ann = jams.Annotation(namespace='tag_open', time=2, duration=8)
>>> ann_trim = ann.trim(5, 8)
>>> print(ann_trim.sandbox)
{
  "trim": [
    {
      "start_time": 5, 
      "trim_start": 5, 
      "end_time": 8, 
      "trim_end": 8
    }
  ]
}
>>> print(ann.sandbox)
{}
```

---

*[jams/core.py, line 1015 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGsfxeBELqXKaKKr1:-KW4bumLw9lavp3BkZh1:b-886gsx) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1015)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Again, provide a short (1-sentence) docstring and then a detailed description.
</details>
Fixed

---

*[jams/core.py, line 1023 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpGyCIbp2Ba-Jno8JH:-KW4fOtFOBkj-cA6uyAF:b-8b11j9) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1023)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> +"in seconds"
</details>
Added

---

*[jams/core.py, line 1039 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpH2gA5L1UveCh6iBb:-KW4gEmuTGeHrF7pGlTW:b-e6u9bg) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1039)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Add a "see also" to trim
> 
> Add an example
</details>

Added see also and example.

---

*[jams/core.py, line 1050 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpH8EltQ7pUmHN07wa:-KW4tm0MjBW_voiGHY4F:b-o7psuy) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1050)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> why would this ever be `None`?
</details>
When I was playing around with this during initial development I seem to have reached this case, but I can't reproduce it, so removing the check for `None`.

---

*[jams/core.py, line 1051 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHDoOOuzgPgC4xhjY:-KW4gpwTC7M22YwPsd8_:b-z1ojeq) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1051)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> This isn't the correct way to iterate over dataframe indices.
> 
> Instead, do
> ```python
> for idx in sliced_ann.data.index:
> ```
> or avoid iteration altogether:
> ```python
> sliced_ann.data['time'] = sliced_ann.data['time'].apply(lambda x: x - pd.to_timedelta(adjustment, unit='s')
> ```
</details>
Switched to lambda function implementation

---

*[jams/core.py, line 1058 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHaw3gH7jiFNgbYeG:-KW4hPg2lpp2m_vbuiVE:bq3rw75) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1058)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> no need for .keys(), and same comments as in `trim` above.
</details>
As noted above with .keys() the call breaks, leaving as is for now.

---

*[jams/core.py, line 1561 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHn7uvieNVSG1GAaD:-KW4uz4SsqPCPajEMkvZ:bnba9zn) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1561)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> I don't see why this should be required here.
</details>
You need it to perform the next check:
```if not (0 <= start_time <= end_time <= float(self.file_metadata.duration)):```

We could do away with this check, but then it would be possible to call `JAMS.trim` with a time range that doesn't (or only partially) intersects with the jam. Would that make sense?

---

*[jams/core.py, line 1567 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpHxBoHukpzPSZTAQX:-KW4q81GQfnUsXmi_2CE:b-fv0ycv) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1567)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> fun fact: python supports triple comparison, so you can do `not (0 <= start_time <= self.file_metadata.duration)`
</details>
Nice, so I can actually do:
```if not (0 <= start_time <= end_time <= float(self.file_metadata.duration)):```

---

*[jams/core.py, line 1576 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpI6Nw8vYIQmiwWtFg:-KW4iTM-mZiPcE_y7_BJ:bv6os21) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1576)):*
I think this does result in a deep copy, no?
```python
>>> jam = jams.JAMS()
>>> jam.file_metadata.duration = 10
>>> jam_trim = jam.trim(5, 8)
>>> print(jam.sandbox)
{}
>>> print(jam_trim.sandbox)
{
  "trim": [
    [
      5, 
      8
    ]
  ]
}
```

---

*[jams/core.py, line 1583 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpID29D2Ai9k1HWX1d:-KW4kLR4aSgRD7VcuX29:b-k5qfvi) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L1583)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> -.keys()
</details>
See previous comments, leaving as is for now.

---

*[tests/jams_test.py, line 732 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpIRvEsagmX55mdBRc:-KW5--TzCt6CfpNSrYgE:b-3f6ivd) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/tests/jams_test.py#L732)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Please break this test into smaller test functions for each test case.
</details>
Broke it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/136)*

**Comment by bmcfee** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[jams/core.py, line 939 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpF1hh2QqKAne3BJte:-KW5-iLUbmv3zJTpctY6:b-7mzr9o) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L939)):*
<details><summary><i>Previously, justinsalamon (Justin Salamon) wrote…</i></summary>
> I need to know the time range spanned by the annotation to compute the intersection with the trim range specified by the user, for which I need `Annotation.duration`.
> 
> Since an Annotation object can exist independently of a JAMS object, while `duration=None` means "use the jams duration", there's no way for me to access this value from inside this function (or the value may not exist).
</details>
Got it.

I think it's also reasonable, in this case, to just override the time/duration fields with the trim interval.  Before trimming, the annotation spans whatever the jams file spans; afterwards, it explicitly spans the specified interval.

The only ambiguous case is when the trim interval overruns file_metadata.duration.  I think this is detectable at the level of `JAMS.trim`, but it's fine to let it slide at the annotation level.

The reason I'm picking on this point is that a lot of annotations do have implicit span, in which case we'd be unable to use trim/slice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/136)*

**Comment by justinsalamon** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[jams/core.py, line 939 at r2](https://reviewable.io:443/reviews/marl/jams/136#-KVpF1hh2QqKAne3BJte:-KW54ok3bNCMH9kqUG-H:b-e4xo3k) ([raw file](https://github.com/marl/jams/blob/30a84724e8ed3b6f0c76d7f95209c56e127e074f/jams/core.py#L939)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> Got it.
> 
> I think it's also reasonable, in this case, to just override the time/duration fields with the trim interval.  Before trimming, the annotation spans whatever the jams file spans; afterwards, it explicitly spans the specified interval.
> 
> The only ambiguous case is when the trim interval overruns file_metadata.duration.  I think this is detectable at the level of `JAMS.trim`, but it's fine to let it slide at the annotation level.
> 
> The reason I'm picking on this point is that a lot of annotations do have implicit span, in which case we'd be unable to use trim/slice.
</details>
Yeah I see your point. Like you say it can lead to some weird behavior (worse than the trim interval overrunning `file_metadata.duration`, it might not even intersect with it at all...). But I guess overall it's better to allow this to happen and trust the user will avoid it, at the benefit of being able to trim annotations that don't have an explicit duration set. Implemented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/136)*

**Comment by bmcfee** [comment]
Reviewed 1 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/jams_test.py, line 983 at r4](https://reviewable.io:443/reviews/marl/jams/136#-KW978RkQ-KIbixIWcCD:-KW978RkQ-KIbixIWcCE:br8cfmy) ([raw file](https://github.com/marl/jams/blob/8de6ab863071196821d0d15d3061d0b99dd63b30/tests/jams_test.py#L983)):*
> ```Python
> def test_jams_trim():
> 
>     @raises(jams.ParameterError, jams.JamsError)
> ```

do you really need both errors here?  it would be better to have separate test cases for separate error triggers.  A catch-all for our package's base exception class is dangerous and could mask other errors.

---

*[tests/jams_test.py, line 997 at r4](https://reviewable.io:443/reviews/marl/jams/136#-KW96wwpIXHL0wmDwdD_:-KW96wwpIXHL0wmDwdDa:bm8rc7z) ([raw file](https://github.com/marl/jams/blob/8de6ab863071196821d0d15d3061d0b99dd63b30/tests/jams_test.py#L997)):*
> ```Python
>     trim_times = [(-5, -1), (-5, 10), (-5, 20), (5, 20), (18, 20), (10, 8)]
>     for tt in trim_times:
>         __test_error(jam, *tt)
> ```

if you `yield __test_error, jam, tt`, each of these cases will show up separately.  this makes debugging easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/136)*

**Comment by justinsalamon** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/jams_test.py, line 983 at r4](https://reviewable.io:443/reviews/marl/jams/136#-KW978RkQ-KIbixIWcCD:-KW9T9O0ik9PN_cpsBDJ:b-zu1ne) ([raw file](https://github.com/marl/jams/blob/8de6ab863071196821d0d15d3061d0b99dd63b30/tests/jams_test.py#L983)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> do you really need both errors here?  it would be better to have separate test cases for separate error triggers.  A catch-all for our package's base exception class is dangerous and could mask other errors.
</details>
OK, I've broken these out into separate tests.

---

*[tests/jams_test.py, line 997 at r4](https://reviewable.io:443/reviews/marl/jams/136#-KW96wwpIXHL0wmDwdD_:-KW9cHcyYpKt0Cl7XNcx:b10suy0) ([raw file](https://github.com/marl/jams/blob/8de6ab863071196821d0d15d3061d0b99dd63b30/tests/jams_test.py#L997)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> if you `yield __test_error, jam, tt`, each of these cases will show up separately.  this makes debugging easier.
</details>
Sure, changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/136)*

**Comment by bmcfee** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/136#-:-KW9dDlio0dDT4i7FKzP:bnfp4nl)*

**Pull request merged**
