### PR TITLE
Partial annotation [implements #66 ]

### PR DESCRIPTION
**Pull request by bmcfee**
Implements #66

### CODE REVIEW

**Comment by bmcfee** [comment]
I've implemented the schema changes as described in #66 .  A couple of things to hammer out before merging:

- Do we want the time/duration fields to be timedeltas (as in the jamsframe) or plain floats?  The latter is simpler and fits with the FileMetadata duration field, but timedeltas would make it fit with jamsframe.

- Should we make them required fields?  Right now it's either a non-negative number or 'null'.  Is this okay with everyone?

**Comment by bmcfee** [comment]
Since nobody's taking my bait, here's my 2e-2€:

> Do we want the time/duration fields to be timedeltas (as in the jamsframe) or plain floats? The latter is simpler and fits with the FileMetadata duration field, but timedeltas would make it fit with jamsframe.

I vote `float` for simplicity and consistency with file_metadata.  (This is a pyjams thing, not a schema thing.)

> Should we make them required fields? Right now it's either a non-negative number or 'null'. Is this okay with everyone?

I don't think we should make them required.


If everyone agrees with me on the above, this PR is ready to merge.

**Comment by justinsalamon** [comment]
:+1:

**Comment by urinieto** [comment]
Sounds good to me too.

**Pull request merged**
