### PR TITLE
added infer_duration flag to import_lab

### LINKED ISSUE #107: Import LAB files from Sonic Visualiser
Hey folks,

when exporting lab-files from Sonic Visualiser (use *.txt for this instead of *.csv),
they export in this structure:
#start_time \t #value \t #duration \t #label

A typical call would then be:

`jams.util.import_lab('segment_open', names=range(4), usecols=[0, 2, 3], sep='\t')`

but I can't overwrite the behaviour that the duration is calculated.

So maybe we could add a flag in the function call to disable this?

### PR DESCRIPTION
**Pull request by bmcfee**
fixes #107

---
This change is [Reviewable](https://reviewable.io/reviews/marl/jams/125)

### CODE REVIEW

**Comment by bmcfee** [comment]
Note: this PR changes the default behavior of `import_lab` on event annotations.

Previously, if there were only two columns on input, then the `duration` field was set to 0 as it was assumed to correspond to instantaneous events.

You can still achieve this behavior by setting `infer_duration=False` for this kind of input, but when the flag is set to `True` (default, to be consistent with interval inputs), duration is computed by the deltas between successive rows.  The final event is assumed to have zero duration.

This may cause hiccups in some data set import scripts.  However, I couldn't think of a better/more consistent way to parameterize this behavior.

**Comment by bmcfee** [comment]
tagging @stefan-balke

**Comment by stefan-balke** [comment]
Will check asap.

**Comment by bmcfee** [comment]
Also tagging @urinieto since it might break some of his import scripts.

**Comment by stefan-balke** [comment]
Tried it and LGTM!

**Comment by bmcfee** [comment]
@urinieto can you take a peek at this and give me your :euro: e-2?

**Comment by bmcfee** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/125)*

**Comment by bmcfee** [comment]
@urinieto timed out!  But note that the salami importer will need to be updated.

**Pull request merged**
