### PR TITLE
added __contains__ to JObject

### PR DESCRIPTION
**Pull request by bmcfee**
Implements #137

---
This change is [Reviewable](https://reviewable.io/reviews/marl/jams/139)

### CODE REVIEW

**Comment by bmcfee** [comment]
@ejhumphrey @justinsalamon care to CR?  should be quick.

**Comment by ejhumphrey** [comment]
I can take a look in an hour?

**Comment by justinsalamon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/jams_test.py, line 129 at r1](https://reviewable.io:443/reviews/marl/jams/139#-KYFjsqFbmzMIClNRL1m:-KYFjsqFbmzMIClNRL1n:b-41ubf6) ([raw file](https://github.com/marl/jams/blob/e0dc215e79f3c113e2175160c68bf18bff4fbc71/tests/jams_test.py#L129)):*
> ```Python
>         assert key in S
> ```

Is there need to add a test for S.keys() ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/139)*

**Comment by justinsalamon** [comment]
Other than that 1 comment, LGTM.

**Comment by bmcfee** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/jams_test.py, line 129 at r1](https://reviewable.io:443/reviews/marl/jams/139#-KYFjsqFbmzMIClNRL1m:-KYFkgJsYOsaXsDySoTe:b-gag673) ([raw file](https://github.com/marl/jams/blob/e0dc215e79f3c113e2175160c68bf18bff4fbc71/tests/jams_test.py#L129)):*
<details><summary><i>Previously, justinsalamon (Justin Salamon) wrote…</i></summary><blockquote>

Is there need to add a test for S.keys() ?
</blockquote></details>

I don't think so?  The existing `keys` method was not touched by this PR, and that functionality is tested elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/139)*

**Comment by justinsalamon** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/139#-:-KYG30KqF4tBXBfMyRvS:bnfp4nl)*

**Comment by justinsalamon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/139)*

**Pull request merged**
