### PR TITLE
Display via mir_eval

### PR DESCRIPTION
**Pull request by bmcfee**
For when mir_eval's display module gets merged.

- [x] implement multi-contour visualization
- [x] write a `pitch_hz` -> `contour_hz` nsconverter
- [x] pitch interval (piano roll) visualizations

---
This change is [Reviewable](https://reviewable.io/reviews/marl/jams/115)

### CODE REVIEW

**Comment by bmcfee** [comment]
Anyone have opinions about how annotation metadata could/should be included in the generated figures?  I was thinking about making a separate subplot joined to the right edge of the main subplot, and populating that with a text box.  Maybe there's a nicer way?

I'd rather not clutter the main figure too much.

**Comment by bmcfee** [comment]
Here's what it looks like now:

```python
fig, _ = jams.display.display_multi(jam.annotations[:3], fig_kw=dict(figsize=(8, 4)))
fig.tight_layout()
```
image

**Comment by urinieto** [comment]
I will quickly chime in to a simply say that I think this is awesome.

**Comment by bmcfee** [comment]
This one is now up to date with the pitch namespace refactor.

`note_*` namespaces will now render as piano rolls.  `pitch_contour` renders contours grouped into colors by id.  If you want a single color for all contours in a plot, you can clobber that by saying `jams.display.display(jam.annotation[i], color='b')` or whatever.

I think this is ready for some serious tire-kicking.  I guess @rabitt and @justinsalamon have the most data that would be useful for testing here.. little help?

**Comment by bmcfee** [comment]
Test coverage is now up to par.

It depends on mir_eval 0.4 though, so we should wait to merge until that's released.

**Comment by stefan-balke** [comment]
@bmcfee there is a missing
`from . import display`

int the `__init__.py`

**Comment by stefan-balke** [comment]
Works, but looks different here.
screen shot 2016-07-28 at 17 01 47

**Comment by bmcfee** [comment]
No there isn't.

`mir_eval` decided to have matplotlib as an optional dependency, so the display module cannot be loaded automatically at the top-level.  JAMS could resolve this by adding an mpl dependency, but given the strange issues around leaking file descriptors and the potential use of JAMS on server-side applications, we decided to keep the optional import.

**Comment by bmcfee** [comment]
> looks different here.

What's your mpl version?

**Comment by stefan-balke** [comment]
> What's your mpl version?
matplotlib (1.5.2)

**Comment by stefan-balke** [comment]
> mir_eval decided to have matplotlib as an optional dependency, so the display module cannot be loaded automatically at the top-level. JAMS could resolve this by adding an mpl dependency, but given the strange issues around leaking file descriptors and the potential use of JAMS on server-side applications, we decided to keep the optional import.

Got it, thanks.

**Comment by stefan-balke** [comment]
Could be a backend problem, couldn't it? Or do you have some fancy settings in your mpl-rc?

BTW:
If you do not use `fig.tight_layout()`, this will happen.

bennycarter_sweetlorraine

**Comment by bmcfee** [comment]
It's almost certainly a theme issue.  I'm not worrying about that for now because mpl 2 will change all the defaults anyway.

If you want to reproduce the examples I pasted, you might try
```python
import matplotlib.style
matplotlib.style.use('seaborn-white')
```
(i think that's what i used, anyway.)

**Comment by stefan-balke** [comment]
Have this now:

`import jams.display
import seaborn
import matplotlib.style
matplotlib.style.use('seaborn-white')
`

That worked. Thanks.
chetbaker_longagoandfaraway

**Comment by ejhumphrey** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/115#-:-KO_zfkWz5wyqng0OmIn:bnfp4nl)*

**Comment by ejhumphrey** [comment]
@bmcfee I'll let you do the honors of the mergy

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/115#-:-KO_znr0LY66kw16ek_e:by92i0o)*

**Comment by ejhumphrey** [comment]
Reviewed 2 of 5 files at r1, 4 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/115)*

**Comment by bmcfee** [comment]
I'll wait on merge until mir_eval releases so I can fix the version in the travis config.

**Comment by bmcfee** [comment]
mir_eval 0.4 is out; i'd like to merge this one today, once all the tests pass.

**Comment by bmcfee** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marl/jams/115)*

**Pull request merged**
